version: '3.3'
services:
  sut:
    build:
      context: tests/app-pip
      dockerfile: $GITHUB_WORKSPACE/python-onbuild/tests/Dockerfile
      args:
        IMAGE_NAME: ${IMAGE_NAME}
    command: -v --lsbsysinit /tests
