name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 2'

env:
  DOCKER_REPO: godatadriven/python-onbuild

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Array where every entry is a single miniconda docker image 
        # represented by a string with comma seperated tags:
        # ["MINICONDA_RELEASE-PYTHON_VERSION,TAG_2, TAG_3, ....", ]
        DOCKER_TAG: [
          "conda-python2.7",
          "conda-python3.6",
          "conda-python3.7",
          "conda-python3.8",
          "conda-python3.9,conda",
          "pip-python2.7",
          "pip-python3.6",
          "pip-python3.7",
          "pip-python3.8",
          "pip-python3.9,pip,latest"
        ]
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
            DOCKER_TAG="${{ matrix.DOCKER_TAG }}"
            IMAGE_TAG=${DOCKER_TAG%%,*}

            DEP_TYPE=${IMAGE_TAG%-*}
            DOCKERFILE="Dockerfile_${DEP_TYPE}"
            echo ::set-output name=dockerfile::${DOCKERFILE}

            PYTHON_TAG=${IMAGE_TAG#*-}
            PYTHON_VERSION=${PYTHON_TAG:6}
            echo ::set-output name=python_version::${PYTHON_VERSION}

            DOCKER_IMAGE_NAME="$DOCKER_REPO:$IMAGE_TAG"
            echo ::set-output name=image_name::${DOCKER_IMAGE_NAME}
            
            TAGS="$DOCKER_REPO:${DOCKER_TAG//,/,$DOCKER_REPO:}"
            echo ::set-output name=tags::${TAGS}

            echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

            echo $(pwd)

      - name: Build image
        uses: docker/build-push-action@v2
        with:
         context: .
         file: ./${{ steps.prep.outputs.dockerfile }}
         push: false
         tags: ${{ steps.prep.outputs.tags }}
         build-args: |
           PYTHON_VERSION=${{ steps.prep.outputs.python_version }}
         labels: |
           org.opencontainers.image.source=${{ github.event.repository.clone_url }}
           org.opencontainers.image.created=${{ steps.prep.outputs.created }}
           org.opencontainers.image.revision=${{ github.sha }}

      - name: Test image
        env:
            IMAGE_NAME: ${{ steps.prep.outputs.image_name }}
        run: |
            if [[ -f "docker-compose.test.yml" ]]; then
                docker-compose --file docker-compose.test.yml build
                docker-compose --file docker-compose.test.yml run sut
            fi

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1 
        with:
          username: nzeilemaker
          password: ${{ secrets.DOCKERHUB }}

      - name: Push image
        if: github.ref == 'refs/heads/master'
        run: |
            docker push $DOCKER_REPO
